---
- name: Gitea Setup | Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Gitea Setup | Print the package facts
  when: ansible_facts.packages['podman'] is undefined
  ansible.builtin.fail:
    msg: "Podman must be present to run"
