---
- name: Gitea Setup | Ensure gitea registry configuration is in place
  ansible.builtin.template:
    src: gitea.conf.j2
    dest: /etc/containers/registries.conf.d/gitea.conf
    mode: 0755
  become: true

- name: Gitea Setup | Ensure ssh config file is present
  ansible.builtin.file:
    path: ~/.ssh/config
    mode: "0600"
    state: file

- name: Gitea Setup | Enable ssh-rsa for localhost
  ansible.builtin.blockinfile:
    block: |
      Host localhost
        HostkeyAlgorithms +ssh-rsa
        PubkeyAcceptedKeyTypes +ssh-rsa
    dest: ~/.ssh/config
    state: present
