---
- name: Install and enable Podman
  ansible.builtin.dnf:
    name:
      - podman
      - firewalld
    state: present
  become: true

- name: Ensure firewalld is installed
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  become: true
