---
# tasks file for ansible-gitea-podman
- name: Include tasks for host setup
  ansible.builtin.include_tasks:
    file: check-podman.yml

- name: Include tasks for host setup
  ansible.builtin.include_tasks:
    file: gitea-config.yml

- name: Include tasks for firewall setup
  ansible.builtin.include_tasks:
    file: firewall-setup.yml

- name: Include tasks for Podman setup
  ansible.builtin.include_tasks:
    file: podman-setup.yml
