---
# tasks file for ansible-gitea-podman
- name: Include tasks
  ansible.builtin.include_tasks:
    file: host-setup.yml

- name: Include tasks
  ansible.builtin.include_tasks:
    file: podman-setup.yml