- name: Gitea Setup | Ensure Gitea container is not present already
  containers.podman.podman_container:
    name: gitea
    state: absent

- name: Gitea Setup | Ensure podman network is not present already
  containers.podman.podman_network:
    name: gitea
    state: absent

- name: Gitea Setup | Configure podman network
  containers.podman.podman_network:
    name: gitea
    disable_dns: false
    internal: false
    recreate: false
    state: present
    
- name: Gitea Setup | Ensure podman volume is not present already
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - gitea-data
    - gitea-config
    
- name: Gitea Setup | Configure podman volume
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: present
  loop:
    - gitea-data
    - gitea-config

- name: Gitea Setup | Create gitea container
  containers.podman.podman_container:
    name: gitea
    network:
      - gitea
    volume:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea

    image: docker.io/gitea/gitea:latest-rootless
    ports:
      - "{{ gitea_ssh_port | default(2222,true) }}:2222"
      - "{{ gitea_web_port | default(3000,true) }}:3000"
    env:
      GITEA__security__INSTALL_LOCK: true
      GITEA__server__ROOT_URL: "http://{{ ansible_fqdn }}:{{ gitea_web_port | default(3000,true) }}"

- name: Gitea Setup | Create admin user for gitea
  ansible.builtin.shell:
    cmd: podman exec gitea gitea admin user create --username {{ gitea_admin_user | default("gitea", true) }} --password {{ gitea_admin_password | default("redhat", true) }} --email {{ gitea_admin_email | default("gitea@admin.admin") }} --admin
