- name: Gitea Setup | Configure podman network
  containers.podman.podman_network:
    name: gitea
    disable_dns: false
    internal: false

- name: Gitea Setup | Configure podman volume
  containers.podman.podman_volume:
    name: gitea

- name: Gitea Setup | Ensure Gitea container is not present already
  containers.podman.podman_container:
    name: gitea
    state: absent

- name: Gitea Setup | Create gitea container
  containers.podman.podman_container:
    name: gitea
    network:
      - gitea
    volume:
      - gitea:/data
    image: docker.io/gitea/gitea:latest-rootless
    ports:
      - "{{ gitea_ssh_port | default(2222,true) }}:2222"
      - "{{ gitea_web_port | default(3000,true) }}:3000"
    env:
      GITEA__security__INSTALL_LOCK: true

- name: Gitea Setup | Create admin user for gitea
  ansible.builtin.shell:
    cmd: podman exec gitea gitea admin user create --username {{ gitea_admin_user }} --password {{ gitea_admin_password }} --email {{ gitea_admin_email }}